kvs_user:
    resource: "@KVSUserBundle/Controller"
    type: annotation 
    prefix: /
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

kvs_profile_edit:
    pattern: /profile/edit
    defaults: { _controller: KVSUserBundle:Profile:edit }

kvs_resetting:
    pattern: /resetting
    defaults: { _controller: KVSUserBundle:Resetting:request }
