KVS\UserBundle\Document\UserMeta:
  fields:
    id:
      id: true
    address:
      type: string 
      nullable: true 
      column: address
    mobile:
      type: string 
      nullable: true 
      column: mobile 
    company:
      type: string 
      nullable: true 
      column: company 
    position:
      type: string 
      nullable: true 
      column: position 
  referenceOne:
    user:
      targetDocument: KVS\UserBundle\Document\User
